### ISSUE TITLE
None of jasmine setup/teardown code is executed when running from `ng test`

### ISSUE THREAD

**Issue by jnorkus** [synapse-wireless-labs/jasmine-marbles#37] opened 2019-04-10 13:36 UTC
This code section
```
if (typeof module === 'object' && module.exports) {
    jasmine.getEnv().beforeAll(function () { return addMatchers(); });
    jasmine.getEnv().beforeEach(function () { return scheduler_1.initTestScheduler(); });
    jasmine.getEnv().afterEach(function () {
        scheduler_1.getTestScheduler().flush();
        scheduler_1.resetTestScheduler();
    });
}
```
is not executed when running from `ng test` because `module.exports` is `undefined`.

**Comment by ComradeCow** [comment] 2019-05-31 13:58
I ran into the same issue updating today.  

Found out it was caused by having our tests compile to ES6/ES2015. Switching the `tsconfig.spec.json` to target ES5 fixed this issue for us - the matchers and schedulers got implicitly initialized after that.

For running tests in ES6 mode, it would be nice to have that jasmine environment set up exported as a function.

**Comment by brandonroberts** [comment] 2019-06-18 20:26
Fixed via https://github.com/synapse-wireless-labs/jasmine-marbles/pull/41

**Closed by brandonroberts** 2019-06-18 20:26 UTC
